plugins {
	id 'com.github.johnrengelman.shadow' version '8.1.1'
	id 'maven-publish'
	id 'java-library'
	id 'net.neoforged.moddev' version '2.0.78'
	id 'idea'
}

//loom {
//	silentMojangMappingsLicense()
//	accessWidenerPath = file("src/main/resources/iris.accesswidener")
//
//	forge {
//		convertAccessWideners = true
//		mixinConfigs = [
//				"mixins.oculus.json",
//				"mixins.oculus.fantastic.json",
//				"mixins.oculus.vertexformat.json",
//				"mixins.oculus.bettermipmaps.json",
//				"mixins.oculus.fixes.maxfpscrash.json",
//				"oculus-batched-entity-rendering.mixins.json",
//				"mixins.oculus.compat.sodium.json",
//				"mixins.oculus.compat.indigo.json",
//				"mixins.oculus.compat.indium.json",
//				"mixins.oculus.compat.dh.json",
//				"mixins.oculus.compat.pixelmon.json"
//		]
//	}
//	mixin.defaultRefmapName = "oculus-mixins-refmap.json"
//}

//configurations {
//	shadow {
//		transitive = false
//	}
//}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)
//sourceCompatibility = JavaVersion.VERSION_17
//targetCompatibility = JavaVersion.VERSION_17

base {
	archivesName = "${project.archives_base_name}-mc${project.minecraft_version}"
}

version = project.mod_version
group = project.maven_group

sourceSets {
	desktop {
	}

	vendored {
		java {
			compileClasspath += main.compileClasspath
		}
	}

	sodiumCompatibility {
		java {
			compileClasspath += main.compileClasspath
			compileClasspath += main.output
		}
	}

	main {
		java {
			compileClasspath += vendored.output
			runtimeClasspath += vendored.output
		}
	}
}
//
//loom {
//	runs {
//		client {
//			mods {
//				oculus {
//					sourceSet sourceSets.desktop
//					sourceSet sourceSets.main
//					sourceSet sourceSets.vendored
//					sourceSet sourceSets.sodiumCompatibility
//				}
//			}
//		}
//	}
//}

neoForge {
	version = project.neo_version

	parchment {
		mappingsVersion = project.parchment_mappings_version
		minecraftVersion = project.parchment_minecraft_version
	}

	runs {
		client {
			client()

			systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
		}

		server {
			server()
			programArgument '--nogui'
			systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
		}

		gameTestServer {
			type = "gameTestServer"
			systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
		}

		data {
			data()
			programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
		}

		configureEach {
			systemProperty 'forge.logging.markers', 'REGISTRIES'

			logLevel = org.slf4j.event.Level.DEBUG
		}
	}

	mods {
		oculus {
					sourceSet sourceSets.desktop
					sourceSet sourceSets.main
					sourceSet sourceSets.vendored
					sourceSet sourceSets.sodiumCompatibility
				}
	}
}

repositories {
	maven {
		name = "CurseForge"
		url = "https://cursemaven.com"
		content {
			includeGroup "curse.maven"
		}
	}
	maven {
		name = "Modrinth"
		url = "https://api.modrinth.com/maven"
		content {
			includeGroup "maven.modrinth"
		}
	}
	maven {
		url "https://maven.blamejared.com/"
	}
	maven {
		url "https://maven.neoforged.net/releases"
	}
	mavenCentral()
}

dependencies {

	//implementation "org.embeddedt:embeddium-${minecraft_version}:${embeddium_version}"
	implementation "maven.modrinth:embeddium:${embeddium_version}"
	compileOnly("maven.modrinth:distanthorizonsapi:3.0.0")

	runtimeOnly(implementation(shadow(project(path: ":glsl-relocated", configuration: "bundledJar")))) {
		transitive = false
	}
	implementation jarJar("io.github.douira:glsl-transformer:2.0.2")
	implementation jarJar("org.anarres:jcpp:1.4.14")
}

//processResources {
//	inputs.property "version", project.version
//
//	filesMatching("META-INF/mods.toml") {
//		expand "version": project.version
//	}
//}

// Include resources generated by data generators.
sourceSets.main.resources { srcDir 'src/generated/resources' }


var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
	var replaceProperties = [
			neo_version            : neo_version,
			neo_version_range      : neo_version_range,
			loader_version_range   : loader_version_range,
			mod_version            : mod_version
	]
	inputs.properties replaceProperties
	expand replaceProperties
	from "src/main/templates"
	into "build/generated/sources/modMetadata"
}

// Include the output of "generateModMetadata" as an input directory for the build
// this works with both building through Gradle and the IDE.
sourceSets.main.resources.srcDir generateModMetadata
// To avoid having to run "generateModMetadata" manually, make it run on every project reload
neoForge.ideSyncTask generateModMetadata

shadowJar {
	configurations = [project.configurations.shadow]

	from jar.archiveFile

	relocate 'org.apache.commons.collections4', 'oculus.org.apache.commons.collections4'

	archiveClassifier.set "shadow"

	manifest {
		attributes(
				'Main-Class': 'net.irisshaders.iris.LaunchWarn'
		)
	}
}
//
//remapJar {
//	inputFile.set shadowJar.archiveFile
//	dependsOn shadowJar
//}

jar {
	from sourceSets.sodiumCompatibility.output
	from sourceSets.vendored.output
	from sourceSets.desktop.output
}

java {
	withSourcesJar()
}

sourcesJar {
	from sourceSets.sodiumCompatibility.allSource
	from sourceSets.vendored.allSource
	from sourceSets.desktop.allSource
}

publishing {
	publications {
		mavenJava(MavenPublication) {
			from components.java
		}
	}

	repositories {
	}
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
	module {
		downloadSources = true
		downloadJavadoc = true
	}
}